# Generated by Django 4.0.6 on 2023-02-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankedBlood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_in_pints",
                    models.PositiveSmallIntegerField(verbose_name="amount in pints"),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("o_positive", "O Positive"),
                            ("o_negative", "O Negative"),
                            ("a_positive", "A Positive"),
                            ("a_negative", "A Negative"),
                            ("b_positive", "B Positive"),
                            ("b_negative", "B Negative"),
                            ("ab_positive", "AB Positive"),
                            ("ab_negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="blood type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "full_name",
                    models.CharField(max_length=60, verbose_name="full name"),
                ),
                (
                    "mobile",
                    models.CharField(max_length=20, verbose_name="mobile number"),
                ),
                (
                    "is_requesting",
                    models.BooleanField(default=True, verbose_name="is requesting"),
                ),
                (
                    "amount_in_pints",
                    models.PositiveSmallIntegerField(verbose_name="amount in pints"),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("o_positive", "O Positive"),
                            ("o_negative", "O Negative"),
                            ("a_positive", "A Positive"),
                            ("a_negative", "A Negative"),
                            ("b_positive", "B Positive"),
                            ("b_negative", "B Negative"),
                            ("ab_positive", "AB Positive"),
                            ("ab_negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="blood type",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(max_length=120, verbose_name="request id"),
                ),
                (
                    "requesting_number",
                    models.CharField(max_length=20, verbose_name="requesting number"),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
