# Generated by Django 4.0.6 on 2023-02-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="name")),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "help_line",
                    models.CharField(max_length=20, verbose_name="help line"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=60, verbose_name="full name"),
                ),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "mobile",
                    models.CharField(max_length=20, verbose_name="mobile number"),
                ),
                (
                    "amount_in_pints",
                    models.PositiveSmallIntegerField(verbose_name="amount in pints"),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("o_positive", "O Positive"),
                            ("o_negative", "O Negative"),
                            ("a_positive", "A Positive"),
                            ("a_negative", "A Negative"),
                            ("b_positive", "B Positive"),
                            ("b_negative", "B Negative"),
                            ("ab_positive", "AB Positive"),
                            ("ab_negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="blood type",
                    ),
                ),
                (
                    "is_requesting",
                    models.BooleanField(default=True, verbose_name="is requesting"),
                ),
                (
                    "request_id",
                    models.CharField(max_length=120, verbose_name="request id"),
                ),
                (
                    "requesting_number",
                    models.CharField(max_length=20, verbose_name="requesting number"),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_requests",
                        to="blood_bank.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_requested"],
            },
        ),
        migrations.CreateModel(
            name="BankedBlood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_in_pints",
                    models.PositiveSmallIntegerField(verbose_name="amount in pints"),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("o_positive", "O Positive"),
                            ("o_negative", "O Negative"),
                            ("a_positive", "A Positive"),
                            ("a_negative", "A Negative"),
                            ("b_positive", "B Positive"),
                            ("b_negative", "B Negative"),
                            ("ab_positive", "AB Positive"),
                            ("ab_negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="blood type",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banked_blood",
                        to="blood_bank.hospital",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(
                fields=[
                    "full_name",
                    "mobile",
                    "is_requesting",
                    "blood_type",
                    "request_id",
                    "date_requested",
                    "requesting_number",
                ],
                name="blood_bank__full_na_687179_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankedblood",
            unique_together={("hospital", "blood_type")},
        ),
    ]
